---
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    env:
      NX_NON_NATIVE_HASHER: true
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: 'Install Node'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 'Yarn Install'
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: 'Yarn Build'
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: 'chmod node modules'
        run: sudo chmod 777 -R /home/runner/work/adrianbadilla/adrianbadilla/node_modules

      - name: 'chmod node dist/apps/'
        run: sudo chmod 777 -R /home/runner/work/adrianbadilla/adrianbadilla/dist/

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADRIANBADILLAFIREBASE }}'
          projectId: adrianbadillafirebase
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
name: 'Deploy to Firebase Hosting on PR'
'on': pull_request
permissions: write-all
